main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: 3.2.7
description: The ultimate moderation plugin!
author: Shortninja
website: http://shortninja.net
softdepend: [PacketListenerApi]
api-version: 1.13
